targetfile: config/targets.txt
gene_target:  config/gene_coordinates.txt
sampledirectory: #Input your sample directory with a trailing / 
annotationfile: config/3_ENSEMBL_CANONICAL_EXON_in_PROTEIN_CODING_GENE_minus_UTR_gencode.v45.annotation.gtf
annotation_no_exon: config/resorted.hg38.genes.mergedintervals.bed
outputpath: #Directory of snakemake 
demographicFile: config/1000G_Sample_Demographic_Info.txt

plot_format: pdf
sample_suffix: sample_suffix.vcf.gz ## replace with sample suffix for your samples
description: #Enter your description

#environments
bedtools-2.31.1: envs/bedtools-2.31.1.yaml
bcftools-1.19: envs/bcftools-1.19.yaml
iPython-8.15.0: envs/iPython-8.15.0.yaml
Rtools-1.1: envs/Rtools-1.1.yaml
