targetfile: config/targets.txt
gene_target:  config/gene_coordinates.txt
sampledirectory: /n/alignments/hemophilia
annotationfile: config/3_ENSEMBL_CANONICAL_EXON_in_PROTEIN_CODING_GENE_minus_UTR_gencode.v45.annotation.gtf
annotation_no_exon: SNP-plot-snake-testing-Waldo/resorted.hg38.genes.mergedintervals.bed
outputpath: /n/zanderson/SNP-plot-snake-testing-Waldo
demographicFile: config/1000G_Sample_Demographic_Info.txt

plot_format: pdf
sample_suffix: .guppy632.sup.withMeth.pass.hg38.clair3.phased.vcf.gz
description: M0412-NP-WGS-hemophilia-80001-HemB-female

#environments
bedtools-2.31.1: envs/bedtools-2.31.1.yaml
bcftools-1.19: envs/bcftools-1.19.yaml
iPython-8.15.0: envs/iPython-8.15.0.yaml
Rtools-1.1: envs/Rtools-1.1.yaml